### ISSUE TITLE
Metadata stalling and critical error

### ISSUE THREAD

**Issue by ninjamstar** [happypandax/happypandax#136]
Recently  a problem has occurred for me when trying to get metadata tags for galleries automatically. It used to be that when I want to get metadata, I would multi select couple galleries, and queue for metadata. Now, the program would just stall, even if it's like 3 galleries in the queue. I would then have to close the entire program and restart. Going into the galleries itself and pressing fetch metadata up top would work, but not doing them through multi select.

I wanted to see what's wrong through the log in client, but that would just sent me a critical error more often than not. Along with that, I would also get disk malformed, or database corrupt or some things like that. 

Latest HPX version
Win 10

Here are my logs and such: https://anonymousfiles.io/k2UNFbLG/

**Comment by twiddli** [comment]
Hello,
I'm not sure how it occurred but somehow one of the database file HPX uses internally got corrupted.
The file in question is named `internals.db` which you can find in the `data` folder. You can safely delete this file without losing your gallery data, and I'm sure this should fix the issue.

Are you aware of any event that might have caused to corruption?
Forcefully closing HPX without any regard is safe for the most part and shouldn't be able to corrupt any file.

**Comment by ninjamstar** [comment]
Ok, so i deleted that internals.db and I started HPX again. When I tried to fetch metadata however, it said that there was no plugin installed, so I went to the plugin page and saw that I needed to install the plugins even though I didnt touch the plugins at all. It then threw this out to me when I pressed the install button:


Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "happypanda\core\db.py", line 3459, in wrapper
  File "happypanda\interface\plugin.py", line 103, in install_plugin
  File "happypanda\core\plugins.py", line 1273, in install_plugin
happypanda.common.exceptions.PluginInstallError: [PluginInstallError|208]: The plugin files have been tampered with, aborting installation for chaika-metadata:55747a41...2a6cb1761ff4
2019-08-09T22:58:09Z <Greenlet at 0x8319608: install_plugin(plugin_id='55747a41-789b-43dd-964a-2a6cb1761ff4')> failed with PluginInstallError

"Error on func 'install_plugin': PluginInstallError('The plugin files have been tampered with, aborting installation for chaika-metadata:55747a41...2a6cb1761ff4',) "


So I deleted the plugins from the plugins folder and re-copied it from github, but it still shows this.

**Comment by ninjamstar** [comment]
Also, to your question, I dont do anything else in HPX besides add galleries and fetch metadata, so not sure what caused the corruption. I dont touch any of the internal folders and files, I mainly do things inside the website itself.

**Comment by ninjamstar** [comment]
Scratch that, I disabled the plugins, and enabled it again and it works. Idk. Anyways, thanks for the help! If it happens again I will post back.

**Comment by ninjamstar** [comment]
Ok, so I deleted internals. Now I resumed back to metadata fetching, and this occured:


  File "happypanda\core\db.py", line 3459, in wrapper
  File "<E:\happypandax0.10.2.win\decorator.pyc:decorator-gen-16>", line 2, in library_view
  File "env\lib\site-packages\dogpile\cache\region.py", line 1272, in get_or_create_for_user_func
  File "env\lib\site-packages\dogpile\cache\region.py", line 879, in get_or_create
  File "env\lib\site-packages\dogpile\lock.py", line 186, in __enter__
  File "env\lib\site-packages\dogpile\lock.py", line 93, in _enter
  File "env\lib\site-packages\dogpile\lock.py", line 182, in _enter_create
  File "env\lib\site-packages\redis\lock.py", line 226, in release
  File "env\lib\site-packages\redis\lock.py", line 232, in do_release
redis.exceptions.LockNotOwnedError: Cannot release a lock that's no longer owned
2019-08-09T23:20:59Z <Greenlet at 0xd7170b8: library_view(item_type=1, page=0, limit=125, view_filter=1, search_query='tag:none', sort_by=4, search_options={'search.regex': False, 'search.case_sensitive': F)> failed with LockNotOwnedError

'An unhandled critical error has occurred '


I didnt do anything besides multi selecting galleries (about 20 of them or so) and then having it queue for metadata. The process ended and then threw me this.

**Comment by ninjamstar** [comment]
Although after a bit, its working fine. So idk what that error was.

**Comment by twiddli** [comment]
The internaldb backend was changed, this will never occur again.
