### ISSUE TITLE
Happy panda x 0.12.2 only displays "[HappypandaError|100]: An unhandled critical error has occurred: ConnectionError" after upgrading to it, but 11.2 is fine

### ISSUE THREAD

**Issue by AwesomeJames2120** [happypandax/happypandax#169]
would any of you know of a way to resolve this? this occours on both fresh installs *and* upgrades. The output also seems to just be outputting random characters/symbols and i assume its not supposed to be doing that
![image](https://user-images.githubusercontent.com/44416823/67628702-3220dd00-f8be-11e9-8fc2-8711272622b4.png)

**Comment by twiddli** [comment]
Hi, can you fill out this form:

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
If applicable, include your ``error.log`` or ``debug.log`` found in ``[HPX]\logs\`` to help identifying your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment:**
 - OS: [e.g. Linux]
 - Browser and browser version [e.g. chrome 61, firefox 60]
 - HPX Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by gy6221** [comment]
Same issue here.

#### Describe the issue
Get the same issue as OP. When opening the library page, get the below error message.

> [HappypandaError|100]: An unhandled critical error has occurred: ConnectionError

#### To Reproduce
Steps to reproduce the behavior:

1. Start a brand new docker container following the installation guide
2. Fix the permission denied issue in datadir & contentdir to allow the container to start.
3. Navigate to the Web GUI and click library.
4. See error

#### Expected behavior
Showing books.

#### Logs
If applicable, include your error.log or debug.log found in [HPX]\logs\ to help identifying your problem.


        Sep-09 07:04:22--ERROR  [server].happypanda.core.server: An unhandled critical error has occurred 
        Traceback (most recent call last):
          File "urllib3/connection.py", line 159, in _new_conn
          File "urllib3/util/connection.py", line 80, in create_connection
          File "urllib3/util/connection.py", line 70, in create_connection
          File "gevent/_socket3.py", line 407, in connect
            raise error(err, strerror(err))
        ConnectionRefusedError: [Errno 111] Connection refused
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "elasticsearch/connection/http_urllib3.py", line 246, in perform_request
          File "urllib3/connectionpool.py", line 638, in urlopen
          File "urllib3/util/retry.py", line 344, in increment
          File "urllib3/packages/six.py", line 686, in reraise
          File "urllib3/connectionpool.py", line 600, in urlopen
          File "urllib3/connectionpool.py", line 354, in _make_request
          File "http/client.py", line 1277, in request
          File "http/client.py", line 1323, in _send_request
          File "http/client.py", line 1272, in endheaders
          File "http/client.py", line 1032, in _send_output
          File "http/client.py", line 972, in send
          File "urllib3/connection.py", line 181, in connect
          File "urllib3/connection.py", line 168, in _new_conn
        urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb67c165390>: Failed to establish a new connection: [Errno 111] Connection refused
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "happypanda/core/server.py", line 624, in advance
          File "</happypandax/happypandax/decorator.pyc:decorator-gen-25>", line 2, in call_functions
          File "happypanda/common/utils.py", line 1214, in only_cache_if
          File "</happypandax/happypandax/decorator.pyc:decorator-gen-24>", line 2, in call_functions
          File "dogpile/cache/region.py", line 1357, in get_or_create_for_user_func
          File "dogpile/cache/region.py", line 959, in get_or_create
          File "dogpile/lock.py", line 185, in __enter__
          File "dogpile/lock.py", line 94, in _enter
          File "dogpile/lock.py", line 178, in _enter_create
          File "dogpile/cache/region.py", line 913, in gen_value
          File "happypanda/core/server.py", line 583, in call_functions
          File "src/gevent/greenlet.py", line 769, in gevent._gevent_cgreenlet.Greenlet.get
          File "src/gevent/greenlet.py", line 364, in gevent._gevent_cgreenlet.Greenlet._raise_exception
          File "gevent/_compat.py", line 65, in reraise
            raise value.with_traceback(tb)
          File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
          File "happypanda/core/db.py", line 4197, in wrapper
          File "</happypandax/happypandax/decorator.pyc:decorator-gen-5>", line 2, in library_view
          File "dogpile/cache/region.py", line 1357, in get_or_create_for_user_func
          File "dogpile/cache/region.py", line 959, in get_or_create
          File "dogpile/lock.py", line 185, in __enter__
          File "dogpile/lock.py", line 94, in _enter
          File "dogpile/lock.py", line 178, in _enter_create
          File "dogpile/cache/region.py", line 913, in gen_value
          File "happypanda/interface/helpers.py", line 115, in wrapper
          File "happypanda/interface/ui.py", line 209, in library_view
          File "happypanda/interface/ui.py", line 85, in _view_helper
          File "happypanda/core/command.py", line 329, in run
          File "happypanda/core/command.py", line 105, in _run
          File "happypanda/core/command.py", line 357, in _main_wrap
          File "happypanda/core/commands/search_cmd.py", line 1536, in main
          File "happypanda/core/commands/search_cmd.py", line 1511, in esearch_match
          File "elasticsearch_dsl/search.py", line 698, in execute
          File "elasticsearch/client/utils.py", line 152, in _wrapped
          File "elasticsearch/client/__init__.py", line 1617, in search
          File "elasticsearch/transport.py", line 390, in perform_request
          File "elasticsearch/transport.py", line 365, in perform_request
          File "elasticsearch/connection/http_urllib3.py", line 258, in perform_request
        elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb67c165390>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb67c165390>: Failed to establish a new connection: [Errno 111] Connection refused)
        Sep-09 07:04:22--ERROR  [server].happypanda.core.server: An error occurred on client message: b'{"session": "c1c1a0252fae4024bbd6a31ce304c215", "name": "webclient", "data": [{"fname": "library_view", "item_type": 1, "page": 0, "limit": 30, "view_filter": 1, "sort_by": 2, "search_options": {"search.regex": false, "search.case_sensitive": false, "search.match_exact": false, "search.match_all_terms": true, "search.children": true}, "__id__": 26}]}' 
        #### Screenshots
        If applicable, add screenshots to help explain your problem.

#### Environment:

OS: Ubuntu 20.04
Browser and browser version Chrome 92
HPX Version 0.13.3
Additional context
N/A
