### ISSUE TITLE
Docker 0.13.2 failed to start

### ISSUE THREAD

**Issue by lukemin** [happypandax/happypandax#215]
To Reproduce

Download latest docker image
Start it with fresh settings (remove any previous config folders)
See error
Logs

date | stream | content
-- | -- | --
2020-08-29 04:38:34 | stdout | Press Ctrl-C to quit
2020-08-29 04:38:34 | stdout | Waiting up to 2 seconds
2020-08-29 04:38:34 | stdout | Sentry is attempting to send 0 pending error messages
2020-08-29 04:38:34 | stdout | 'Could not establish connection to ESearch server, aborting. '
2020-08-29 04:38:19 | stdout | 'Failed to configure built-in ESearch server, process exit code: still running; also see /data/logs/esearch_stdout.log '
2020-08-29 04:36:11 | stdout | Starting up, please wait...
2020-08-29 04:35:51 | stdout | Using sqlite database
2020-08-29 04:35:50 | stdout | Running HPX version 0.13.2
2020-08-29 04:35:50 | stdout | HPX_DATA was defined, data will now be at: /data
2020-08-29 04:35:50 | stdout |  
2020-08-29 04:35:50 | stdout | -- .- -.-- --- .. ? -.-- .- -.- ..- -- --- ? -.-- .- -- ..
2020-08-29 04:35:50 | stdout | `--'    `--'    `---'
2020-08-29 04:35:50 | stdout | `--'  `--'  `--`--' \|  \|-'  \|  \|-'  .-'  /    `--'       `--`--' `--''--'  `---'   `--`--'   '--'   '--'
2020-08-29 04:35:50 | stdout | \|  \|  \|  \| \ '-'  \| \| '-' ' \| '-' '   \   '   \|  \| --'  \ '-'  \| \|  \|\|  \| \ `-' \| \ '-'  \|    /  .'.  \
2020-08-29 04:35:50 | stdout | \|  .--.  \| ' ,-.  \| \| .-. \| \| .-. \|  \  '  /  \|  '--' \| ' ,-.  \| \|      \ ' .-. \| ' ,-.  \|     .'    \
2020-08-29 04:35:50 | stdout | \|  '--'  \|  ,--,--.  ,---.   ,---.  ,--. ,--. \|  .--. '  ,--,--. ,--,--,   ,-\|  \|  ,--,--.    \  `.'  /
2020-08-29 04:35:50 | stdout | ,--.  ,--.                                    ,------.                       ,--.            ,--.   ,--.
2020-08-29 04:35:50 | stdout |  
2020-08-29 04:35:50 | stdout | Running HPX version 0.13.2

OS: Docker Image
HPX Version 0.13.2 running on synology diskstation

**Comment by reluce** [comment]
It's the same issue where it tries to run elasticsearch as root:

```
$ cat data/logs/esearch_stdout.log
[ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [happypandax-momo_lacus_emilia] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.7.1.jar:7.7.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.7.1.jar:7.7.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.7.1.jar:7.7.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.7.1.jar:7.7.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.7.1.jar:7.7.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.7.1.jar:7.7.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.7.1.jar:7.7.1]
Caused by: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:111) ~[elasticsearch-7.7.1.jar:7.7.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178) ~[elasticsearch-7.7.1.jar:7.7.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.7.1.jar:7.7.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.7.1.jar:7.7.1]
        ... 6 more
uncaught exception in thread [main]
java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:111)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
```

How are you installing/running elasticsearch inside the container? Maybe spinning up a separate container for elasticsearch would be better?

**Comment by waz1500** [comment]
Yep. Docker image still isn't working for me. 
Deleted previous config folder and re-installed. Same error as https://github.com/happypandax/happypandax/issues/210

There is a elasticsearch docker container we could use to link with happypandax. 
https://hub.docker.com/_/elasticsearch

Then we could configure the happypandax docker to accept variables such as 

ElasticSearch host, 
ElasticSearch port
ElasticSearch username
ElasticSearch password

**Comment by twiddli** [comment]
Hello, can you try running `docker pull twiddly/happypandax:latest` now?

**Comment by waz1500** [comment]
Perfect. Pulled the latest version and it's working now for me. Tested also on Unraid server.

**Comment by twiddli** [comment]
should be fixed then
