### ISSUE TITLE
Command ReIndex(155) raised an exception

### ISSUE THREAD

**Issue by MrX292** [happypandax/happypandax#217]
**Describe the issue**
After updating from v0.12.4 to v0.13.2 the gallery showed 0 galleries so i reindexed the Library.
But Nothing Shows up after it is finished.

**To Reproduce**
1. Go to About
2. Click on Reindex library
3. Get the Error in Output and no galleries show up.

**Expected behavior**
The Galleriess in the db should show up.

**Logs**
error.log
```
Aug-08 15:26:39--ERROR  [command].happypanda.core.services: Command ReIndex(155) raised an exception 
Traceback (most recent call last):
  File "happypanda\core\services.py", line 451, in _callback_wrapper
  File "src\\gevent\\greenlet.py", line 769, in gevent._gevent_cgreenlet.Greenlet.get
  File "src\\gevent\\greenlet.py", line 364, in gevent._gevent_cgreenlet.Greenlet._raise_exception
  File "gevent\_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "src\\gevent\\greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "happypanda\core\db.py", line 4210, in wrapper
  File "happypanda\core\command.py", line 105, in _run
  File "happypanda\core\command.py", line 357, in _main_wrap
  File "happypanda\core\commands\meta_cmd.py", line 911, in main
  File "happypanda\core\async_utils.py", line 347, in get
  File "src\\gevent\\greenlet.py", line 795, in gevent._gevent_cgreenlet.Greenlet.get
  File "src\\gevent\\greenlet.py", line 364, in gevent._gevent_cgreenlet.Greenlet._raise_exception
  File "gevent\_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "src\\gevent\\greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "gevent\pool.py", line 90, in apply_cb
    result = self.apply(func, args, kwds)
  File "gevent\pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src\\gevent\\event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "gevent\_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "gevent\threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
  File "happypanda\core\async_utils.py", line 453, in wrapper
  File "happypanda\core\async_utils.py", line 435, in cleanup_wrapper
  File "happypanda\core\commands\meta_cmd.py", line 929, in _reindex
  File "happypanda\core\db_esearch.py", line 630, in reindex
  File "happypanda\core\db_esearch.py", line 129, in reindex
  File "happypanda\core\db_esearch.py", line 136, in _reindex
  File "happypanda\core\db_esearch.py", line 82, in bulk
  File "more_itertools\recipes.py", line 137, in consume
  File "elasticsearch\helpers\actions.py", line 285, in streaming_bulk
  File "elasticsearch\helpers\actions.py", line 141, in _chunk_actions
  File "happypanda\core\db_esearch.py", line 55, in _bulk_doc
  File "happypanda\core\db_esearch.py", line 135, in <genexpr>
  File "happypanda\core\db_esearch.py", line 525, in build
  File "happypanda\core\db_esearch.py", line 370, in build
AttributeError: 'NoneType' object has no attribute 'status'
```

**Environment:**
 - OS: Windows 10
 - chrome , firefox , HappyPanda X Desktop Client
 - HPX Version  0.13.2
 - dialect: postgresql

**Additional context**
Reindex works up to Reindex last 100 items everything over gives the error

**Comment by twiddli** [comment]
Please try out `v0.13.3`. Reopen the issue if it still persists.
