### ISSUE TITLE
Long File Path download issue.

### ISSUE THREAD

**Issue by Devinator12** [happypandax/happypandax#220]
Hey there!

I'm having an issue retrieving a gallery that has a name that extends beyond the system file path length.

Sep-09 19:07:47--WARNING happypanda.migrate: Failed to remove data/internals.db. Please remove it yourself. 
Sep-09 19:10:13--ERROR  [command].happypanda.core.services: Task Download(None) in service download raised an exception 
Traceback (most recent call last):
  File "happypanda\core\services.py", line 642, in _run_task
  File "happypanda\core\command.py", line 588, in _run
  File "happypanda\core\command.py", line 105, in _run
  File "happypanda\core\command.py", line 357, in _main_wrap
  File "happypanda\core\commands\download_cmd.py", line 590, in main
  File "happypanda\core\commands\download_cmd.py", line 765, in _download_requests
  File "happypanda\core\command.py", line 329, in run
  File "happypanda\core\command.py", line 105, in _run
  File "happypanda\core\command.py", line 357, in _main_wrap
  File "happypanda\core\commands\download_cmd.py", line 895, in main
  File "happypanda\core\commands\download_cmd.py", line 980, in download
  File "happypanda\core\commands\network_cmd.py", line 226, in save
  File "happypanda\core\commands\io_cmd.py", line 666, in open
  File "happypanda\core\commands\io_cmd.py", line 320, in __init__
  File "happypanda\core\commands\io_cmd.py", line 657, in _open
FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\C\\Random Nam, ERandom Name (RandomNa meRandom, NameRand omNameRa)] nomNameRan domName (Rand omNameR andomNameR) [andomNa] =meR= [andomNa]\\Random Nam, ERandom Name (RandomNa meRandom, NameRand omNameRa)] nomNameRan domName (Rand omNameR andomNameR) [andomNa] =meR= [andomNa].zip'

Attempting to put the file there myself through explorer causes windows errors about the path being too long. And any other archives have gone through just fine.

Thank you for your time.

**Comment by twiddli** [comment]
Omg not again. Can you maybe try this? https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/
I'm pretty sure I did everything I could from the application-side.

**Comment by Devinator12** [comment]
I'm on Windows 10 Home Version	10.0.19041 Build 19041.
I attempted to do Enable the override in the registry causes the app to go bonkers. Sure it worked for like... 5 pages and then errors just kept pilling up.

I do have a recommendation though. When it makes the download folder for the archive instead of naming it the exact same as the tittle/zip archive name it as the gallery token.

So it would look something like "Z:\C\1234567\Random Nam, ERandom Name (RandomNa meRandom, NameRand omNameRa)] nomNameRan domName (Rand omNameR andomNameR) [andomNa] =meR= [andomNa].zip

This would solve the issue I believe.
