### ISSUE TITLE
Postgres DB with duplicate entries

### ISSUE THREAD

**Issue by glop102** [happypandax/happypandax#226]
I was really hammering the system and doing silly things just to see what HPX can do

1) It was throwing errors about duplicate entries when trying to move a doujin from
   the inbox to the library, and the same item was showing up in both the inbox and
   the library
2) similar duplicate entry error when attempting to update the last read page of the item
   So it always says it was page 18 that was last read

How it got to this terrible state:
- import all 2088 doujins at once
- let it parse the metadata (all plugins enabled)
- have two clients open at the same time to watch the metadata parsing happen
- also have it load the gallery a couple times while the parsing is happening
- also click buttons because i was impatient after a couple hours

Reproducibility? Not sure how to do it consistently but perhaps you can add in better protections either to prevent duplicates or to remove duplicates when encountered.
I am attaching the full data directory of HPX ~~and the DB for postgres~~ (looks like i missed grabbing the database, sorry)
[data_slim.zip](https://github.com/happypandax/happypandax/files/5446152/data_slim.zip)

I am happy to try recreating this problem again if there are other things you want. (such as debug mode being enabled)

**Environment:**
 - OS: Linux - Docker containers
 - Firefox 81.0.2
 - HPX Version 13.3 (server)

**Comment by glop102** [comment]
I hit this a second time, unfortunately it happened the first time i tried to import some things without debug mode on :(
I grabbed the whole database this time.
This has happened using the exact same instance in the ticket #227 before i cleaned it up to make it fresh. (only difference is restarting HPX after turning off debug mode)

Interesting thing of note : in the ticket 227, there were items in the library that i could view and worked correctly. This time the library was empty when the server started and then i went to scan the new items in.
Is this perhaps somehow related to non-working or maybe just non-existant shutdown code and so things don't get flushed that need to be?

```
Oct-10 03:48:58--ERROR  [command].happypanda.core.commands.database_cmd: An error occurred when adding item 
Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 1277, in _execute_context
  File "sqlalchemy/engine/default.py", line 593, in do_execute
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "uq_namespace_tags_userdata_user_id"
DETAIL:  Key (user_id, parent_id)=(2, 43) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "happypanda/core/commands/database_cmd.py", line 1219, in _add_to_db
  File "happypanda/core/commands/database_cmd.py", line 1170, in _add_item
  File "sqlalchemy/orm/session.py", line 1042, in commit
  File "sqlalchemy/orm/session.py", line 504, in commit
  File "sqlalchemy/orm/session.py", line 483, in _prepare_impl
  File "sqlalchemy/orm/session.py", line 2523, in flush
  File "sqlalchemy/orm/session.py", line 2664, in _flush
  File "sqlalchemy/util/langhelpers.py", line 69, in __exit__
  File "sqlalchemy/util/compat.py", line 182, in raise_
  File "sqlalchemy/orm/session.py", line 2624, in _flush
  File "sqlalchemy/orm/unitofwork.py", line 419, in execute
  File "sqlalchemy/orm/unitofwork.py", line 521, in execute_aggregate
  File "sqlalchemy/orm/unitofwork.py", line 589, in execute
  File "sqlalchemy/orm/persistence.py", line 245, in save_obj
  File "sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
  File "sqlalchemy/engine/base.py", line 1011, in execute
  File "sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
  File "sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
  File "sqlalchemy/engine/base.py", line 1317, in _execute_context
  File "sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
  File "sqlalchemy/util/compat.py", line 182, in raise_
  File "sqlalchemy/engine/base.py", line 1277, in _execute_context
  File "sqlalchemy/engine/default.py", line 593, in do_execute
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_namespace_tags_userdata_user_id"
DETAIL:  Key (user_id, parent_id)=(2, 43) already exists.

[SQL: INSERT INTO namespace_tags_userdata (timestamp, _properties, last_updated, user_id, parent_id) VALUES (%(timestamp)s, %(_properties)s, %(last_updated)s, %(user_id)s, %(parent_id)s) RETURNING namespace_tags_userdata.id]
[parameters: {'timestamp': datetime.datetime(2020, 10, 29, 3, 48, 56, 59177), '_properties': '{}', 'last_updated': datetime.datetime(2020, 10, 29, 3, 48, 56, 59258), 'user_id': 2, 'parent_id': 43}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
Oct-10 03:49:00--WARNING [command].happypanda.core.commands.database_cmd: Item adding was completed with errors: 
Oct-10 03:49:00--ERROR  [command].happypanda.core.commands.database_cmd: [
    'Traceback (most recent call last):\n',
    '  File "sqlalchemy/engine/base.py", line 1277, in _execute_context\n',
    '  File "sqlalchemy/engine/default.py", line 593, in do_execute\n',
    'psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "uq_namespace_tags_userdata_user_id"\nDETAIL:  Key (user_id, parent_id)=(2, 43) already exists.\n\n',
    '\nThe above exception was the direct cause of the following exception:\n\n',
    'Traceback (most recent call last):\n',
    '  File "happypanda/core/commands/database_cmd.py", line 1219, in _add_to_db\n',
    '  File "happypanda/core/commands/database_cmd.py", line 1170, in _add_item\n',
    '  File "sqlalchemy/orm/session.py", line 1042, in commit\n',
    '  File "sqlalchemy/orm/session.py", line 504, in commit\n',
    '  File "sqlalchemy/orm/session.py", line 483, in _prepare_impl\n',
    '  File "sqlalchemy/orm/session.py", line 2523, in flush\n',
    '  File "sqlalchemy/orm/session.py", line 2664, in _flush\n',
    '  File "sqlalchemy/util/langhelpers.py", line 69, in __exit__\n',
    '  File "sqlalchemy/util/compat.py", line 182, in raise_\n',
    '  File "sqlalchemy/orm/session.py", line 2624, in _flush\n',
    '  File "sqlalchemy/orm/unitofwork.py", line 419, in execute\n',
    '  File "sqlalchemy/orm/unitofwork.py", line 521, in execute_aggregate\n',
    '  File "sqlalchemy/orm/unitofwork.py", line 589, in execute\n',
    '  File "sqlalchemy/orm/persistence.py", line 245, in save_obj\n',
    '  File "sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements\n',
    '  File "sqlalchemy/engine/base.py", line 1011, in execute\n',
    '  File "sqlalchemy/sql/elements.py", line 298, in _execute_on_connection\n',
    '  File "sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement\n',
    '  File "sqlalchemy/engine/base.py", line 1317, in _execute_context\n',
    '  File "sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception\n',
    '  File "sqlalchemy/util/compat.py", line 182, in raise_\n',
    '  File "sqlalchemy/engine/base.py", line 1277, in _execute_context\n',
    '  File "sqlalchemy/engine/default.py", line 593, in do_execute\n',
    'sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_namespace_tags_userdata_user_id"\nDETAIL:  Key (user_id, parent_id)=(2, 43) already exists.\n\n[SQL: INSERT INTO namespace_tags_userdata (timestamp, _properties, last_updated, user_id, parent_id) VALUES (%(timestamp)s, %(_properties)s, %(last_updated)s, %(user_id)s, %(parent_id)s) RETURNING namespace_tags_userdata.id]\n[parameters: {\'timestamp\': datetime.datetime(2020, 10, 29, 3, 48, 56, 59177), \'_properties\': \'{}\', \'last_updated\': datetime.datetime(2020, 10, 29, 3, 48, 56, 59258), \'user_id\': 2, \'parent_id\': 43}]\n(Background on this error at: http://sqlalche.me/e/13/gkpj)\n',
] 
Oct-10 03:49:00--WARNING [command].happypanda.core.commands.database_cmd: Item import failed from():
	 (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_namespace_tags_userdata_user_id"
DETAIL:  Key (user_id, parent_id)=(2, 43) already exists.

[SQL: INSERT INTO namespace_tags_userdata (timestamp, _properties, last_updated, user_id, parent_id) VALUES (%(timestamp)s, %(_properties)s, %(last_updated)s, %(user_id)s, %(parent_id)s) RETURNING namespace_tags_userdata.id]
[parameters: {'timestamp': datetime.datetime(2020, 10, 29, 3, 48, 56, 59177), '_properties': '{}', 'last_updated': datetime.datetime(2020, 10, 29, 3, 48, 56, 59258), 'user_id': 2, 'parent_id': 43}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```
