### ISSUE TITLE
Syntax error near "PRAGMA foreign_keys=1"

### ISSUE THREAD

**Issue by glop102** [happypandax/happypandax#232]
Accidentally caused some syntax error somehow
Left it running on an import of 1000 files and it started hitting this error after I navigated to the metadata page, not before
It does not seem to be impacting the parsing.

Logs (was in debug mode when this happened)
https://glop.tech/var/www/html/hpx_state4.zip

```
Oct-10 00:19:53--ERROR  [server].happypanda.core.server: A database error occured 
Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
  File "sqlalchemy/pool/base.py", line 364, in connect
  File "sqlalchemy/pool/base.py", line 778, in _checkout
  File "sqlalchemy/pool/base.py", line 495, in checkout
  File "sqlalchemy/pool/impl.py", line 140, in _do_get
  File "sqlalchemy/util/langhelpers.py", line 69, in __exit__
  File "sqlalchemy/util/compat.py", line 182, in raise_
  File "sqlalchemy/pool/impl.py", line 137, in _do_get
  File "sqlalchemy/pool/base.py", line 309, in _create_connection
  File "sqlalchemy/pool/base.py", line 440, in __init__
  File "sqlalchemy/pool/base.py", line 668, in __connect
  File "sqlalchemy/event/attr.py", line 320, in __call__
  File "happypanda/core/db.py", line 3397, in engine_connect
psycopg2.errors.SyntaxError: syntax error at or near "PRAGMA"
LINE 1: PRAGMA foreign_keys=1;
        ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "happypanda/core/server.py", line 624, in advance
  File "</happypandax/happypandax/decorator.pyc:decorator-gen-25>", line 2, in call_functions
  File "happypanda/common/utils.py", line 1217, in only_cache_if
  File "happypanda/core/server.py", line 583, in call_functions
  File "src/gevent/greenlet.py", line 769, in gevent._gevent_cgreenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 364, in gevent._gevent_cgreenlet.Greenlet._raise_exception
  File "gevent/_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "happypanda/core/db.py", line 4197, in wrapper
  File "</happypandax/happypandax/decorator.pyc:decorator-gen-6>", line 2, in get_item
  File "dogpile/cache/region.py", line 1357, in get_or_create_for_user_func
  File "dogpile/cache/region.py", line 959, in get_or_create
  File "dogpile/lock.py", line 185, in __enter__
  File "dogpile/lock.py", line 94, in _enter
  File "dogpile/lock.py", line 178, in _enter_create
  File "dogpile/cache/region.py", line 913, in gen_value
  File "happypanda/interface/helpers.py", line 115, in wrapper
  File "happypanda/interface/database.py", line 250, in get_item
  File "happypanda/core/command.py", line 329, in run
  File "happypanda/core/command.py", line 105, in _run
  File "happypanda/core/command.py", line 357, in _main_wrap
  File "happypanda/core/commands/database_cmd.py", line 968, in main
  File "sqlalchemy/orm/query.py", line 1018, in get
  File "sqlalchemy/orm/query.py", line 1135, in _get_impl
  File "sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
  File "sqlalchemy/orm/query.py", line 3463, in one
  File "sqlalchemy/orm/query.py", line 3432, in one_or_none
  File "sqlalchemy/orm/query.py", line 3508, in __iter__
  File "sqlalchemy/orm/query.py", line 3530, in _execute_and_instances
  File "sqlalchemy/orm/query.py", line 3545, in _get_bind_args
  File "sqlalchemy/orm/query.py", line 3523, in _connection_from_session
  File "sqlalchemy/orm/session.py", line 1141, in connection
  File "sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
  File "sqlalchemy/orm/session.py", line 433, in _connection_for_bind
  File "sqlalchemy/engine/base.py", line 2304, in _contextual_connect
  File "sqlalchemy/engine/base.py", line 2342, in _wrap_pool_connect
  File "sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
  File "sqlalchemy/util/compat.py", line 182, in raise_
  File "sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
  File "sqlalchemy/pool/base.py", line 364, in connect
  File "sqlalchemy/pool/base.py", line 778, in _checkout
  File "sqlalchemy/pool/base.py", line 495, in checkout
  File "sqlalchemy/pool/impl.py", line 140, in _do_get
  File "sqlalchemy/util/langhelpers.py", line 69, in __exit__
  File "sqlalchemy/util/compat.py", line 182, in raise_
  File "sqlalchemy/pool/impl.py", line 137, in _do_get
  File "sqlalchemy/pool/base.py", line 309, in _create_connection
  File "sqlalchemy/pool/base.py", line 440, in __init__
  File "sqlalchemy/pool/base.py", line 668, in __connect
  File "sqlalchemy/event/attr.py", line 320, in __call__
  File "happypanda/core/db.py", line 3397, in engine_connect
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "PRAGMA"
LINE 1: PRAGMA foreign_keys=1;
```

**Comment by twiddli** [comment]
This is a weird issue that I'm not entirely sure how is happening.
You are using the postgresql dialect, right? In you're config.yaml:
```
db:
    dialect: postgres
```
?

**Comment by lionhoho** [comment]
Got exactly the same problem

Nov-11 00:20:45--ERROR  [server].happypanda.core.server: A database error occured 
Traceback (most recent call last):
  File "sqlalchemy\engine\base.py", line 2338, in _wrap_pool_connect
  File "sqlalchemy\pool\base.py", line 364, in connect
  File "sqlalchemy\pool\base.py", line 778, in _checkout
  File "sqlalchemy\pool\base.py", line 495, in checkout
  File "sqlalchemy\pool\impl.py", line 140, in _do_get
  File "sqlalchemy\util\langhelpers.py", line 69, in __exit__
  File "sqlalchemy\util\compat.py", line 182, in raise_
  File "sqlalchemy\pool\impl.py", line 137, in _do_get
  File "sqlalchemy\pool\base.py", line 309, in _create_connection
  File "sqlalchemy\pool\base.py", line 440, in __init__
  File "sqlalchemy\pool\base.py", line 668, in __connect
  File "sqlalchemy\event\attr.py", line 320, in __call__
  File "happypanda\core\db.py", line 3397, in engine_connect
psycopg2.errors.SyntaxError: syntax error at or near "PRAGMA"
LINE 1: PRAGMA foreign_keys=1;
        ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "happypanda\core\server.py", line 624, in advance
  File "<D:\HappyPandaX\decorator.pyc:decorator-gen-25>", line 2, in call_functions
  File "happypanda\common\utils.py", line 1217, in only_cache_if
  File "happypanda\core\server.py", line 583, in call_functions
  File "src\\gevent\\greenlet.py", line 769, in gevent._gevent_cgreenlet.Greenlet.get
  File "src\\gevent\\greenlet.py", line 364, in gevent._gevent_cgreenlet.Greenlet._raise_exception
  File "gevent\_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "src\\gevent\\greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "happypanda\core\db.py", line 4197, in wrapper
  File "<D:\HappyPandaX\decorator.pyc:decorator-gen-12>", line 2, in get_items
  File "dogpile\cache\region.py", line 1357, in get_or_create_for_user_func
  File "dogpile\cache\region.py", line 959, in get_or_create
  File "dogpile\lock.py", line 185, in __enter__
  File "dogpile\lock.py", line 94, in _enter
  File "dogpile\lock.py", line 178, in _enter_create
  File "dogpile\cache\region.py", line 913, in gen_value
  File "happypanda\interface\helpers.py", line 115, in wrapper
  File "happypanda\interface\database.py", line 314, in get_items
  File "happypanda\core\command.py", line 329, in run
  File "happypanda\core\command.py", line 105, in _run
  File "happypanda\core\command.py", line 357, in _main_wrap
  File "happypanda\core\commands\database_cmd.py", line 973, in main
  File "happypanda\core\commands\database_cmd.py", line 842, in _query
  File "sqlalchemy\orm\query.py", line 3346, in all
  File "sqlalchemy\orm\query.py", line 3508, in __iter__
  File "sqlalchemy\orm\query.py", line 3530, in _execute_and_instances
  File "sqlalchemy\orm\query.py", line 3545, in _get_bind_args
  File "sqlalchemy\orm\query.py", line 3523, in _connection_from_session
  File "sqlalchemy\orm\session.py", line 1141, in connection
  File "sqlalchemy\orm\session.py", line 1147, in _connection_for_bind
  File "sqlalchemy\orm\session.py", line 433, in _connection_for_bind
  File "sqlalchemy\engine\base.py", line 2304, in _contextual_connect
  File "sqlalchemy\engine\base.py", line 2342, in _wrap_pool_connect
  File "sqlalchemy\engine\base.py", line 1584, in _handle_dbapi_exception_noconnection
  File "sqlalchemy\util\compat.py", line 182, in raise_
  File "sqlalchemy\engine\base.py", line 2338, in _wrap_pool_connect
  File "sqlalchemy\pool\base.py", line 364, in connect
  File "sqlalchemy\pool\base.py", line 778, in _checkout
  File "sqlalchemy\pool\base.py", line 495, in checkout
  File "sqlalchemy\pool\impl.py", line 140, in _do_get
  File "sqlalchemy\util\langhelpers.py", line 69, in __exit__
  File "sqlalchemy\util\compat.py", line 182, in raise_
  File "sqlalchemy\pool\impl.py", line 137, in _do_get
  File "sqlalchemy\pool\base.py", line 309, in _create_connection
  File "sqlalchemy\pool\base.py", line 440, in __init__
  File "sqlalchemy\pool\base.py", line 668, in __connect
  File "sqlalchemy\event\attr.py", line 320, in __call__
  File "happypanda\core\db.py", line 3397, in engine_connect
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "PRAGMA"
LINE 1: PRAGMA foreign_keys=1;
        ^

(Background on this error at: http://sqlalche.me/e/13/f405)
