### ISSUE TITLE
unable to install plugins using docker-compose

### ISSUE THREAD

**Issue by ramenchef** [happypandax/happypandax#237]
**Describe the issue**
I get a permission error when attempting to install plugins 

**To Reproduce**
follow installation instructions using docker-compose
log into default user account
go to About > Plugins and click install on any plugin

**Expected behavior**
Plugin installs

**Logs**
PermissionError: [Errno 1] Operation not permitted
Jan-01 08:27:29--ERROR  [server].happypanda.core.server: An error occurred on client message: b'{"session": "4df1b8c868704f37b089971cd6a4cae4", "name": "webclient", "data": [{"fname": "install_plugin", "plugin_id": "efaec768-760c-49d7-8d45-fb70b7db45e5", "__id__": 105}]}' 
Jan-01 08:27:30--ERROR  [server].happypanda.core.server: An unhandled critical error has occurred 
Traceback (most recent call last):
  File "happypanda/core/server.py", line 624, in advance
  File "</happypandax/happypandax/decorator.pyc:decorator-gen-25>", line 2, in call_functions
  File "happypanda/common/utils.py", line 1217, in only_cache_if
  File "happypanda/core/server.py", line 583, in call_functions
  File "src/gevent/greenlet.py", line 769, in gevent._gevent_cgreenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 364, in gevent._gevent_cgreenlet.Greenlet._raise_exception
  File "gevent/_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "happypanda/core/db.py", line 4197, in wrapper
  File "happypanda/core/db.py", line 4321, in w
  File "happypanda/interface/plugin.py", line 105, in install_plugin
  File "happypanda/core/plugins.py", line 1263, in install_plugin
  File "shutil.py", line 267, in copy2
  File "shutil.py", line 206, in copystat
PermissionError: [Errno 1] Operation not permitted
Jan-01 08:27:30--ERROR  [server].happypanda.core.server: An error occurred on client message: b'{"session": "4df1b8c868704f37b089971cd6a4cae4", "name": "webclient", "data": [{"fname": "install_plugin", "plugin_id": "efaec768-760c-49d7-8d45-fb70b7db45e5", "__id__": 107}, {"fname": "get_plugin", "plugin_id": "efaec768-760c-49d7-8d45-fb70b7db45e5", "__id__": 108}]}' 

**Environment:**
 - OS: Windows 10 64-bit. Docker using WSL2 engine
 - Browser and browser version: chrome 87
 - HPX Version v0.13.3

**Comment by jababda** [comment]
Any updates on this? I've just run into the problem about 2 years on from when this was posted.
