### ISSUE TITLE
UnsupportedOperation: seek

### ISSUE THREAD

**Issue by LeadingChip** [happypandax/happypandax#72]
**Describe the bug**
Everytime it has to create a thumbnail it gives errors, the thumbnails are created correctly tho.

**To Reproduce**
1. Add new books
2. Wait for thumbs to load
3. Errors in the console

**Expected behavior**
No errors

**Logs**
```Python
Traceback (most recent call last):
  File "env\lib\site-packages\gevent\threadpool.py", line 211, in _worker
io.UnsupportedOperation: seek
Mon Nov  5 15:45:19 2018 (<ThreadPool at 0x7b8b870 0/1/10>, <built-in method seek of ZipExtFile object at 0x00CC6130>) failed with UnsupportedOperation
```

**Environment:**
 - OS: Windows 10 LTSB 1607
 - Browser and browser version: Firefox 63
 - HPX Version: 0.5.2

**Comment by mkahvi** [comment]
This is still a problem. I used the scan feature to add multiple archives (zip and cbz files).

>(<ThreadPool at 0x83b94b0 0/2/10 hub=<Hub at 0x83ba138 thread_ident=0x17520>>, <built-in method seek of ZipExtFile object at 0x100538D0>) failed with UnsupportedOperation
>Traceback (most recent call last):
>File "env\lib\site-packages\gevent\threadpool.py", line 281, in _worker
>io.UnsupportedOperation: seek

**Comment by twiddli** [comment]
It's a harmless error. I just need to silence it.
