### ISSUE TITLE
Scan fails to scan, File is not a zip file while it clearly is

### ISSUE THREAD

**Issue by mrskizzex** [happypandax/happypandax#84]
**Describe the bug**
Scan fails to read files from directory.

**To Reproduce**
Well this is kinda hard to reproduce when its related to files on my computer but : 
1. Go to 'http://localhost:7008/add/scan'
2. Enter directory path and Click on 'Scan'
3. See nothing 
https://my.mixtape.moe/oqoagz.webm screen recording

**Expected behavior**
I guess correct scan behaviour ?

**Logs**
```
Dec-12 22:51:44--ERROR  [command].happypanda.core.services: Command ScanGallery(229) raised an exception 
Traceback (most recent call last):
  File "happypanda\core\services.py", line 442, in _callback_wrapper
  File "src\gevent\greenlet.py", line 633, in gevent._greenlet.Greenlet.get
  File "src\gevent\greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "env\lib\site-packages\gevent\_compat.py", line 47, in reraise
  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "happypanda\core\db.py", line 2715, in wrapper
  File "happypanda\core\command.py", line 94, in _run
  File "happypanda\core\command.py", line 309, in _main_wrap
  File "happypanda\core\commands\gallery_cmd.py", line 115, in main
  File "happypanda\core\async_utils.py", line 187, in get
  File "src\gevent\greenlet.py", line 659, in gevent._greenlet.Greenlet.get
  File "src\gevent\greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "env\lib\site-packages\gevent\_compat.py", line 47, in reraise
  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "env\lib\site-packages\gevent\pool.py", line 88, in apply_cb
  File "env\lib\site-packages\gevent\pool.py", line 159, in apply
  File "src\gevent\event.py", line 381, in gevent._event.AsyncResult.get
  File "src\gevent\event.py", line 409, in gevent._event.AsyncResult.get
  File "src\gevent\event.py", line 399, in gevent._event.AsyncResult.get
  File "src\gevent\event.py", line 379, in gevent._event.AsyncResult._raise_exception
  File "env\lib\site-packages\gevent\_compat.py", line 47, in reraise
  File "env\lib\site-packages\gevent\threadpool.py", line 281, in _worker
  File "happypanda\core\async_utils.py", line 288, in wrapper
  File "happypanda\core\async_utils.py", line 274, in cleanup_wrapper
  File "happypanda\core\commands\gallery_cmd.py", line 86, in _generate_gallery_fs
  File "happypanda\core\commands\io_cmd.py", line 1060, in load_all
  File "happypanda\core\commands\io_cmd.py", line 1151, in load_pages
  File "happypanda\core\commands\io_cmd.py", line 485, in contents
  File "happypanda\core\commands\io_cmd.py", line 623, in _init_archive
  File "happypanda\core\commands\io_cmd.py", line 772, in __init__
  File "happypanda\core\plugins.py", line 460, in first_or_none
  File "happypanda\core\plugins.py", line 584, in _call_node_idx
  File "happypanda\core\plugins.py", line 555, in _call_capture
  File "happypanda\core\commands\io_cmd.py", line 806, in _init_def
  File "zipfile.py", line 1108, in __init__
  File "zipfile.py", line 1175, in _RealGetContents
zipfile.BadZipFile: File is not a zip file

```

**Screenshots**
7-Zip test of all files in the directory, I checked that one error about CRC of one image but its still viewable and openable in CDisplayEX
https://i.imgur.com/YHQeScs.png

**Environment:**
 - OS: Windows
 - Browser: Chromium 71.0.3578.98 
 - HPX Version: 0.6.1

**Additional context**
```
 Directory of G:\HH\HH\#

13.12.2018  22:00    <DIR>          .
13.12.2018  22:00    <DIR>          ..
27.12.2017  13:54        33 981 040 [.7 (DAWY)] Onee-sama na Succubus to Josou Santa-chan｜｜Mature Succubus and Young Santa-chan [English].cbz
26.12.2017  02:30        38 155 553 [.7 (DAWY)] Sakuya, Saku 1 [English] [mysterymeat3].cbz
24.06.2017  16:42         5 555 272 [100yen Locker] Uchi no Maou-sama   The overlord in my house (COMIC Penguin Club 2016-01) [English] [葛葛のの寺寺].cbz
26.12.2017  02:31        20 424 517 [10pasec no Kanata (Satsuki Neko)] Naganami Summer Sweet (Kantai Collection -KanColle-) [English] [Sekrit_Klub].cbz
04.08.2018  06:58        48 998 620 [110-GROOVE (Itou Yuuji)] Sakuya-san vs Meiling-san (Touhou Project) [English] {Doujins.com}.cbz
18.06.2018  22:04        54 376 047 [110-GROOVE (Itou Yuuji)] Yakumo Ran no Kyouikuteki Shidou (Touhou Project) [English].cbz
01.10.2018  15:37        66 822 916 [110-GROOVE (Itou Yuuji)] Youmu's Coming of Age (Touhou Project) [English] [Yajuu Scans].cbz
25.10.2018  19:15        39 397 828 [140km h (Akagi Asahito)] Sukoshi Furyouppoi Onnanoko to Kyuujitsu ni Ie de Daradara Shitai Hon. [English] [tracesnull] [2017-11-10].cbz
16.08.2017  22:49        76 578 325 [212] Himitsu no Manabiya   The Secret School (Aimitsu Carameliser) [English] [N04H].cbz
21.07.2017  17:20       107 511 330 [21kg (Kito)] Teki no Shoi de Futanari ni sareta Ladybug ga Cat Noir no Shojo wo Ubacchau hon (Miraculous Ladybug) [English] {Shotachan}.cbz
24.07.2018  22:47        32 035 960 [28_works (Oomori Harusame)] KMB (Monster Hunter) [English] [SneakyTranslations].cbz
08.01.2018  22:44        62 111 079 [2nd color (Typehatena)] Chimametai ga Tabegoro datta no de Oishiku Itadaichaimashita    The Chimame-Tai was about ready to eat so I dug right in (Gochuumon wa Usagi desu ka ) [English].cbz
26.12.2017  02:31        49 740 158 [2nd color (Typehatena)] I Wanted to Be Lovey-Dovey with Chino-chan so Much I Overdid it My Affection Returned to Me in 120% (Gochuumon wa Usagi desu ka)[English].cbz
26.12.2017  02:31        11 484 811 [2nd color (Typehatena)] Kigumi no Machi o Aruitetara Oishisou na Kodomo ga Ita node Gochisou ni Narimashita (Gochuumon wa Usagi desu ka ) [English] {Hennojin} [Digital].cbz
15.08.2018  14:02        79 441 592 [2nd color (Typehatena)] Loli Harem Shujinkou ni (Saimin de) Nattemita   I tried out being a loli-harem protagonist (with the help of a little hypnosis) (Ryuuou no Oshigoto!) [English].cbz
09.05.2018  13:33         6 533 645 [2nd color (Typehatena)] Uma Musume Tanetsuke Koubi Show   Horse Girl Breeding Show (Uma Musume Pretty Derby) [English] [slathe].cbz
16.08.2018  22:29        32 149 263 [40010 1-GO (40010Prototype)] CHOYGEDO! (Kono Subarashii Sekai ni Syukufuku o!) [English] [AJS].cbz
16.03.2017  03:51        16 221 493 [40010 1-GO (Shimanto Shisakugata)] Loose Yui (COMIC Kairakuten 2015-08).cbz
29.11.2017  16:33        22 272 833 [40010 1-GO (Shimanto Shisakugata)] Rito-SAN in the Bath (Prototype Orange Mikan Hon Soushuuhen) (To LOVE-Ru) [English] [animefan71109].cbz
17.06.2017  12:40        13 733 171 [40010 1-GO (Shimanto Shisakugata)] Souyuu Reisou (Fate kaleid liner Prisma Illya) [English] [Mongolfier].cbz
27.03.2018  03:20        82 238 856 [40010 1-GO (Shimanto Shisakugata)] Souyuu Reisou 2 (Fate kaleid liner Prisma Illya) [English] [mongolfier].cbz
25.08.2017  23:58        51 834 161 [40010 1-GO (Shimanto Shisakugata)] Souyuu Reisou+ (Fate kaleid liner Prisma Illya) [English] [Mongolfier].cbz
21.03.2017  08:46        24 622 219 [40010 1-GO (Shimanto Shisakugata)] Tomodachi no Ecchi na Kyoudai Kankei (To Love-Ru) [English] {doujins.com} [Decensored].cbz
31.03.2017  02:52        14 066 073 [40010 1-GO (Shimanto Shisakugata)] Wished World,Debauched World (To Love-Ru) [English] [Cecilbk].cbz
01.06.2017  23:54        13 563 165 [40010 Prototype] Black2 Train (COMIC Kairakuten 2017-05).cbz
16.03.2017  03:51        11 988 406 [40010 Prototype] Bug Zapper (COMIC Kairakuten 2015-12).cbz
15.09.2017  00:07        21 228 631 [40denier (Shinooka Homare)] Chi-tan Ijiri (Danganronpa) [English].cbz
17.03.2017  04:34        65 734 606 [40Denier (Shinooka Homare)] Nuinui no Shasei Kanri   Nuinui's Ejaculation Management (Kantai Collection -KanColle-) [English] [Hennojin] [Digital].cbz
31.07.2017  14:50        13 110 195 [50on! (Aiue Oka)] Saimin Seishidou 2.5 Keika Kansatu [English] [Reitaimimizu].cbz
25.11.2018  03:15        36 844 473 [54BURGER (Marugoshi)] Flan-chan no Pet   Flan-chan's Pet (Touhou Project) [English] [S.T.A.L.K.E.R].cbz
23.09.2018  10:00       115 050 626 [6 centimeter] Mesugao Bishounen ga YariCir de Yuumei na TenniCir ni Haittara _E...  Ore ga Yarareru no ka yo! _   I Have a Girly Face, but If I Join This Tennis Club Where Everyone Gets Laid... Wait, I'm the Bottom ! [English.cbz
24.02.2018  15:35        80 232 442 [666PROTECT (Jingrock)] Ame ni Nurenishi Hanabira no. (Koi wa Ameagari no You ni) [English] [desudesu].cbz
15.09.2018  21:30        18 818 186 [666protect (Jingrock)] fortissimo (K-ON!) [English] [Yoroshii].cbz
19.03.2017  07:00        16 096 546 [70 Nenshiki Yuukyuu Kikan (Endou Okito)] Elf no Yomeiri   Elven Bride [English] [YQII].cbz
16.03.2017  03:32        53 793 186 [70 Nenshiki Yuukyuu Kikan (Ohagi-san)] pictulia + 4P Leaflet [English] [An_chan].cbz
20.05.2018  11:26       215 211 937 [70 Nenshiki Yuukyuu Kikan (Ohagi-san)] Sen no Ko o Haramu Mori no Shoujo - The girl of the woods with a thousand young (Fate Grand Order) [English] =White Symphony=.cbz
11.11.2017  14:38        68 261 163 [774 House (774)] Hadakahime Honoka 2 Misemono Tanetsuke Saru Koubi   Naked Princess Honoka 2 - Mating Exhibition- Monkey Coitus [English] {5 a.m.}.cbz
11.11.2017  14:38        79 553 977 [774 House (774)] Hadakahime Honoka Zecchou Kakusei Buta Koubi   Naked Princess Honoka - Awakening to Pig-Mating Orgasms [English] =LWB=.cbz
11.11.2017  14:38       134 418 550 [774 House (774)] Suzuka-sama no Geboku   Suzuka-sama's Servant [English] [Trinity Translations Team]{Detexted}.cbz
25.01.2018  16:08       230 008 705 [774House (774)] Hadakahime Honoka San Kyodai Osubuta vs Chounouryoku Shoujo! [English] [pepedid119].cbz
31.03.2017  02:52        33 820 997 [774] C91 Kaijou Genteibon (Fate kaleid liner Prisma Illya) [English] [Mongolfier].cbz
05.10.2018  05:35        14 027 167 [88 Gou (Ooishi Chuuni)] Eromanjiru Sensei (Eromanga Sensei) [English] [Robo Scans].cbz
              42 File(s)  2 212 049 720 bytes
               2 Dir(s)  338 256 351 232 bytes free
```

**Comment by twiddli** [comment]
Hello, can you try pinpointing the file causing the issue and importing it at `/add/new/gallery`

**Comment by mrskizzex** [comment]
Sure, [this](https://my.mixtape.moe/gzfjcs.cbz) is one of the files that causes it. 

```
Dec-12 17:16:48--ERROR  [server].happypanda.core.server: An unhandled critical error has occurred 
Traceback (most recent call last):
  File "happypanda\core\server.py", line 447, in advance
  File "happypanda\interface\gallery.py", line 264, in load_gallery_from_path
  File "happypanda\core\commands\io_cmd.py", line 1151, in load_pages
  File "happypanda\core\commands\io_cmd.py", line 485, in contents
  File "happypanda\core\commands\io_cmd.py", line 623, in _init_archive
  File "happypanda\core\commands\io_cmd.py", line 772, in __init__
  File "happypanda\core\plugins.py", line 460, in first_or_none
  File "happypanda\core\plugins.py", line 584, in _call_node_idx
  File "happypanda\core\plugins.py", line 555, in _call_capture
  File "happypanda\core\commands\io_cmd.py", line 806, in _init_def
  File "zipfile.py", line 1108, in __init__
  File "zipfile.py", line 1175, in _RealGetContents
zipfile.BadZipFile: File is not a zip file

```

**Comment by mrskizzex** [comment]
Okay. I found out what is going on. The zip file indeed isn't a zip file. its 7z. CDisplayEX and 7zip has no problem when trying to open it but I guess your implementation only can read normal zip files.

To fix this problem I propose two things that you could try to do : 
1. Add a 7z read capability.
2. Skip file read errors and after adding all files that are okay print list of files that couldn't be read and maybe add a note that user should check the actual compression used to zip the file.

Of course, no pressure. You can close this issue if you want, I will fix it myself with some scripting magic.

**Comment by twiddli** [comment]
Hi, your suggestions sound good. You could create an issue for each of them so I don't forget.
